NAME: DeepFashion_s2
SAVE_DIR: runs

MODEL:
  LOCAL:
    ENABLE: True

SOLVER:
  DECAY_RATE: 0.9
  STEP_SIZE: 1
  EPOCHS: 20
  GLOBAL_WEIGHT: 1.
  ALIGN_WEIGHT: 0.1
  LOCAL_WEIGHT: 0.1
  BASE_LR: 1e-4
  BASE_LR_SLOW: 1e-5
INPUT:
  THRESHOLD: 0.1